### ISSUE TITLE
No module named 'openwisp_utils.admin_theme.menu'

### ISSUE THREAD

**Issue by Harishrelysys** [openwisp/openwisp-utils#265] opened 2021-11-17 12:51 UTC
Hi All,
I am trying to host openwisp server and openwisp-monitoring in digital ocean server. I am able to host openwisp2 through ansible and able to configure my openwrt router through openwisp. But when i try to install and run openwisp-monitoring i am getting error as bellow

error:
========

/opt/openwisp2/env/bin/python ./manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'openwisp_utils.admin_theme' has no attribute 'menu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 136, in create
    import_module(entry)
  File "/opt/openwisp2/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openwisp_utils.admin_theme.menu'

**Comment by nemesisdesign** [comment] 2021-11-17 16:09
This error indicates that you're missing the new menu utilities of openwisp-utils, hence you installed a development version of openwisp monitoring which needs the development version of openwisp-utils. You need to upgrade openwisp-utils to the latest mastr.

If you want to use the development version of the OpenWISP modules (upcoming release), the recommended way is to use these instructions of the ansible role: https://github.com/openwisp/ansible-openwisp2/tree/dev#deploying-the-upcoming-release-of-openwisp.

I am closing because it's not a bug report, for further requests please use the [support channels](https://openwisp.org/support.html).

**Closed by nemesisdesign** 2021-11-17 16:09 UTC
